apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcp-store
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: arcanna-postgres-credentials
        property: user
    - secretKey: password
      remoteRef:
        key: arcanna-postgres-credentials
        property: password
    - secretKey: database
      remoteRef:
        key: arcanna-postgres-credentials
        property: database