apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.region }}
          clusterName: {{ .Values.clusterName }}
          clusterProjectID: {{ .Values.projectID }}
          serviceAccountRef:
            name: external-secrets
            namespace: {{ .Release.Namespace }}